ARG VERSION=20H2-amd64

FROM mcr.microsoft.com/windows/servercore:$VERSION

# Download msys2
RUN setx /M path "%PATH%;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl" && \
    powershell -Command "curl.exe -L "https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe" --output msys2.exe" && \
    msys2.exe && \
    del msys2.exe

# Update msys2 and install some tools
RUN bash -lc 'pacman --needed --noconfirm -Syuu' && \
    bash -lc 'pacman --needed --noconfirm -Syuu' && \
    bash -lc 'pacman --needed --noconfirm -Scc' && \
    bash -lc 'pacman --needed --noconfirm -S curl wget git patch rsync base-devel bison flex texinfo ninja meson make unzip nano vim && \
    bash -lc 'rm -fr /C/Users/ContainerUser/* /var/cache/pacman/pkg/*' && \
    mklink /J C:\\msys64\\home\\ContainerUser C:\\Users\\ContainerUser && \
    setx HOME "C:\msys64\home\ContainerUser"

WORKDIR C:\\msys64\\home\\ContainerUser\\
CMD ["bash", "-l"]