ARG VERSION=latest

FROM hatsum/msys2:$VERSION

ARG MSYSTEM=MINGW64

COPY scripts\\msys2-qemu-dependencies.sh C:\\msys64\\home\\ContainerUser\\
ADD virgil3d\\MINGW-packages C:\\msys64\\home\\ContainerUser\\virgil3d\\

# Install dependencies
RUN bash -lc "./msys2-qemu-dependencies.sh" && \
    bash -lc 'rm -vfr /var/cache/pacman/pkg/* /home/ContainerUser/*'

WORKDIR C:\\msys64\\home\\ContainerUser\\
CMD ["bash", "-l"]